; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = uno

[env:uno]
platform = atmelavr
board = uno
framework = arduino

[env:nano]
platform = atmelavr
board = nanoatmega328
framework = arduino
board_build.mcu = atmega328p
board_build.f_cpu = 16000000L

[env:nano_new]
platform = atmelavr
board = nanoatmega328new
framework = arduino
board_build.mcu = atmega328p
board_build.f_cpu = 16000000L

[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
board_build.mcu = esp32c3
board_build.f_cpu = 160000000L
framework = arduino

build_flags =
  -DESP_BUILD=1
  -DESP_EN_PIN=0
  -DESP_OW_PIN=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
  -DARDUINO_TINYUSB=1
  -DCORE_DEBUG_LEVEL=5  ; Set the debug level (0-5, with 5 being the most verbose)

lib_deps = 

monitor_filters = 
    esp32_exception_decoder
    time      ; Add timestamp with milliseconds for each new line