[env:nano]
platform = atmelavr
board = nanoatmega328
framework = arduino
board_build.mcu = atmega328p
board_build.f_cpu = 16000000L
lib_deps =
    adafruit/Adafruit SSD1306@^2.5.7
    adafruit/Adafruit GFX Library@^1.11.5
monitor_speed = 9600
